minimum_dollars_delta: 0.0001
do_transactions: false
regenerate_cycles: true
regenerate_denom2symbol: true
fees: 2700
xatol: 0.1
fatol: 0.1
account: "osmo123kgn90rmdcrhas5fu2anfvnyrhvgurlk7j4es"
sleep_time: 1