minimum_dollars_delta: 30000
do_transactions: false
regenerate_cycles: true
regenerate_denom2symbol: true
fees: 2700
xatol: 10000
fatol: 100
account: "osmo123kgn90rmdcrhas5fu2anfvnyrhvgurlk7j4es"
sleep_time: 1